name: Teste Cliente

on:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.artifact-name }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm clean-install
        env:
          OCTAURA_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm test
